apiVersion: v1
kind: Pod
metadata:
  labels:
    app: stirling-pdf-ci-agent
spec:
  serviceAccountName: jenkins-agent
  containers:
    - name: docker
      image: docker:27-dind
      securityContext:
        privileged: true
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
      volumeMounts:
        - name: docker-storage
          mountPath: /var/lib/docker
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 2000m
          memory: 3Gi

    - name: helm
      image: alpine/helm:3.14.0
      command: ["cat"]
      tty: true
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi

  volumes:
    - name: docker-storage
      emptyDir: {}

  restartPolicy: Never
